[workspace]
resolver = "3"
members = ["crates/*"]
default-members = []

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "BSD-3-Clause"
authors = ["hikari <me@metantesan.com>"]
repository = "https://github.com/metantesan/fuin"

[workspace.dependencies]

[workspace.lints.rust]
unsafe_code = "forbid"
unused_imports = "warn"
unused_variables = "warn"
dead_code = "warn"
[workspace.lints.clippy]
unwrap_used = "deny"
