name: Build and Deploy  Helm charts

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    concurrency: deploy-${{ github.ref }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/checkout@v7
        with:
          ref: gh-pages
          path: out

      - uses: azure/setup-helm@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: lint charts
        run: helm lint charts/fuin

      - name: package charts
        run: helm package charts/fuin --destination out

      - name: update chart index
        run: helm repo index out --url "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
